[profile.default]
solc = '0.8.23'
evm_version = 'paris'                   # Required for L2s (Optimism, Arbitrum, etc.)
sizes = true
verbosity = 3                           # display errors
optimizer_runs = 200
runs = 4096
libs = ["node_modules", "lib"]

[fmt]
number_underscore = "thousands"
multiline_func_header = "all"
wrap_comments = true
